### ISSUE TITLE
Index 페이지 제작

### ISSUE THREAD

**Issue by wogns3623** [wogns3623/Neotube#3]
### Index페이지 제작
- 처음 접속하면 보일 페이지를 React 구조에 맞춰 설계, 제작하기

**Comment by jae-hun-e** [comment]
내일 3pm까지 메인화면 리엑트 구조 구상해오기!

**Comment by wogns3623** [comment]
### 뷰 설계

#### 레이아웃
* 4단계로 나뉨
  1. 헤더 아이템들이 전부 존재하고 왼쪽 메뉴 확장 시 메인 컨테이너 영역을 차지함
  2. 헤더 아이템들은 전부 존재하지만 왼쪽 메뉴 확장 시 오버레이 형식으로 표시됨
  3. 헤더 아이템들은 전부 존재하지만 왼쪽 기본 메뉴가 사라짐
  4. 헤더 아이템중 검색 창이 사라짐

* 메인 컨테이너(영상들이 들어가는 공간)는 크기가 줄어들 수록 영상 크기도 함께 줄어들지만 영상 크기가 일정 이상 줄어들면 대신 한 줄에 들어가는 영상의 수가 줄어듬

main
- overlay
  - header(top nav)
    - menu
      - item(btn, logo, search bar)
        * only img except search bar
      - dropdown menu
        * if item is dropdown menu, it has > on right side
        * another overlay
        * only one dropdown overlay at a time
  - popup player

  - left nav
    * this is kind of overlay too
    - menu
      - item(linkable)
        * img-desc  형태
        * 더보기 버튼도 이 컴포넌트에서 파생
          - 더보기 버튼은 아이템 개수가 일정 이상일경우 {count}개 더보기 형식으로 표시됨
    - footer

- main feed
  - video container(뉴스피드, 추천 영상란 등)
    - video box
      - thumbnail
      - channel thumnail
      - title
      - channel title
      - views
        * 절대 4자리를 넘어가지 않음
        * 10000만 -> 1억
      - posted date

  - community container
    - community box
      - channel thumnail
      - channel title
      - posted date
      - content
      - more(optional)
      - image or video link
      - good/bad/comment box
        - good( img-num shape)
        - bad( only img )
        - comment( same as good )

**Comment by jae-hun-e** [comment]
![영상 컴포넌트](https://user-images.githubusercontent.com/76520477/106562297-75f89c80-656d-11eb-909f-7f3ff5de46bc.png)

요거는 영상 컴포넌트 봐본거야
