### ISSUE TITLE
DB 구조, api 설계 및 구현

### ISSUE THREAD

**Issue by wogns3623** [wogns3623/Neotube#4]
- DB 스키마 구조와 RESTful 하도록 api 구현하기

**Comment by sunsuking** [comment]
{ Default : [channel, title, video, gif, thumbnail, runtime, views, createtime],
Add :[channel, title, video, gif, thumbnail, runtime, views, createtime]
}

**Comment by sunsuking** [comment]
{video: [ {channel: junsu, title: [상여자] 라이벌, video: video/2021/10/02/05/21/상여자_라이벌.mp4, thumbnail: thumbnail/2021/10/02/05/21/fiveDice.png, runtime: 192, views: 1, create_at: 2021년 2월 5일 1:10 오전} , {channel: junsu, title: 신세계 트레이더스? 정용진 '백화점, 이마트 그리고 야구장까지', video: video/2021/11/02/05/21/신세계_트레이더스__정용진_백화점_이마트_그리고_야구장까지___14F.mp4, thumbnail: thumbnail/2021/11/02/05/21/twoDice.png, runtime: 78, views: 5, create_at: 2021년 2월 5일 1:11 오전} ] user: { username: null, img: null } }
